#!/usr/bin/bash

branch_name=$(git rev-parse --abbrev-ref HEAD)
valid_branch_pattern=$'^(feature|hotfix)/[a-z0-9-]+$'

if [[ ! $branch_name =~ $valid_branch_pattern ]]; then
    echo "Error: '$branch_name' is not a valid branch name."
    echo "Please use: feature/* hotfix/*"
    exit 1
fi

echo "Valid branch name"
exit 0